//  Code generated by pkgalias. DO NOT EDIT.
//  exporting symbols from fmt
//  github.com/sean9999/pkgalias

package fmt

import (
	"fmt"
)

//	variables


//	functions
var FormatString = fmt.FormatString
var Fprintf = fmt.Fprintf
var Sprintf = fmt.Sprintf
var Appendf = fmt.Appendf
var Fprint = fmt.Fprint
var Print = fmt.Print
var Sprint = fmt.Sprint
var Append = fmt.Append
var Fprintln = fmt.Fprintln
var Sprintln = fmt.Sprintln
var Appendln = fmt.Appendln
var Scan = fmt.Scan
var Scanln = fmt.Scanln
var Scanf = fmt.Scanf
var Sscan = fmt.Sscan
var Sscanln = fmt.Sscanln
var Sscanf = fmt.Sscanf
var Fscan = fmt.Fscan
var Fscanln = fmt.Fscanln
var Fscanf = fmt.Fscanf


//	interfaces

type State interface {
	fmt.State
}
type Formatter interface {
	fmt.Formatter
}
type Stringer interface {
	fmt.Stringer
}
type GoStringer interface {
	fmt.GoStringer
}
type ScanState interface {
	fmt.ScanState
}
type Scanner interface {
	fmt.Scanner
}