//  Code generated by pkgalias. DO NOT EDIT.
//  exporting symbols from fmt
//  github.com/sean9999/pkgalias

package fmt

import (
	"fmt"
)

//	variables


//	functions
var Errorf = fmt.Errorf
var FormatString = fmt.FormatString
var Fprintf = fmt.Fprintf
var Sprintf = fmt.Sprintf
var Appendf = fmt.Appendf
var Fprint = fmt.Fprint
var Sprint = fmt.Sprint
var Append = fmt.Append
var Fprintln = fmt.Fprintln
var Sprintln = fmt.Sprintln
var Appendln = fmt.Appendln
var Sscan = fmt.Sscan
var Sscanln = fmt.Sscanln
var Sscanf = fmt.Sscanf
var Fscan = fmt.Fscan
var Fscanln = fmt.Fscanln
var Fscanf = fmt.Fscanf


//	interfaces
type State = fmt.State
type Formatter = fmt.Formatter
type Stringer = fmt.Stringer
type GoStringer = fmt.GoStringer
type ScanState = fmt.ScanState
type Scanner = fmt.Scanner
